<?php

namespace App\Http\Requests\Admin\User;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize():bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules():array
    {
        return [
            'name' => 'nullable',
            'email' => 'nullable ',
            'password' => 'confirmed | nullable | min:2'
        ];
    }

    public function validated():array
    {
        $data =  parent::validated(); // TODO: Change the autogenerated stub

        if (!empty($data['password'])) {
            $data['password'] = bcrypt($data['password']);
        }

        return array_filter($data);
    }
}
