<?php

namespace App\Http\Requests\Api\Comment;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize():bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules():array
    {
        return [
            'comment' => 'nullable | String',
            'title' => 'nullable | String',
            'rating' => 'nullable | int',
        ];
    }

    public function validated():array
    {
        return array_filter(parent::validated()); // TODO: Change the autogenerated stub
    }
}
