<?php

namespace App\Http\Requests\User\Comment;


use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize():bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'description' => 'required',
            'title' => 'required',
            'rating' => 'int',

        ];
    }

    public function validated():array
    {
        $data =  parent::validated(); // TODO: Change the autogenerated stub

        $data['user_id'] = $this->user()->id;

        return $data;
    }
}
