<?php

namespace App\Http\Requests\User\Comment;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Validator;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules():array
    {
        return [
            'title' => 'nullable',
            'description' => 'nullable',
            'rating' => 'nullable',
        ];
    }

    public function validated():array
    {
        return array_filter(parent::validated()); // TODO: Change the autogenerated stub
    }

    public function withValidator($validator)
    {
        $validator->after(function ($validator) {
            if (!$this->userIsValid()) {
               return $validator->errors()->add('field', 'Вы не являетесь автором комментария');
            }
        });
    }

    private function userIsValid()
    {
        $comment = $this->route('comment');

        return $this->user()->can('protected-comment', $comment);
    }
}
